In [3]:
## This practice is designed for Universal Functions, Indexing, Slicing and Iterating
import numpy as np

In [4]:
### Universal Functions
B = np.arange(3)
print("B=> {0}".format(B))

B=>
[0 1 2]


In [5]:
B_exp = np.exp(B)
print("B_exp=> {0}".format(B_exp))

B_exp=>
[1.         2.71828183 7.3890561 ]


In [6]:
B_sqrt = np.sqrt(B)
print("B_sqrt=> {0}".format(B_sqrt))

B_sqrt=>
[0.         1.         1.41421356]


In [7]:
C = np.array([2, 1, 0])
print("B add C=> {0}".format(np.add(B, C)))

B add C=>
[2 2 2]


In [25]:
## Indexing, Slicing and Iterating
# 只有一維陣列可以被 indexed, sliced, iterated over

# indexed
a = np.arange(10) ** 2
print("a**2=> {0}".format(a))
print()
print("a[2:5]=> {0}".format(a[2:5]))
print()

# sliced
# 從陣列起始算起可以被2整除的index的元素值都改為9999，直到第7個元素(index為6)為止
a[:7:2] = 9999
print("a[:7:2]=> {0}".format(a))
print()
# reversed
print("a[: : -1])=> {0}".format(a[: : -1]))
print()

# Iteracted over
for i in a:
    print("a**(1/2)=> {0}".format(np.round(i**(1/2), 0)))

a**2=> [ 0  1  4  9 16 25 36 49 64 81]

a[2:5]=> [ 4  9 16]

a[:7:2]=> [9999    1 9999    9 9999   25 9999   49   64   81]

a[: : -1])=> [  81   64   49 9999   25 9999    9 9999    1 9999]

a**(1/2)=> 100.0
a**(1/2)=> 1.0
a**(1/2)=> 100.0
a**(1/2)=> 3.0
a**(1/2)=> 100.0
a**(1/2)=> 5.0
a**(1/2)=> 100.0
a**(1/2)=> 7.0
a**(1/2)=> 8.0
a**(1/2)=> 9.0


In [38]:
## Form function
def my_f(row, col):
    return row*5 + col

b = np.fromfunction(my_f, (5, 5), dtype=int)
print(b)

print(b[3:5, 4])
print(b[:, 4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[19 24]
[ 4  9 14 19 24]
