In [1]:
import numpy as np

In [2]:
##Shape Manipulation
# 矩陣的形狀
# the shape of matrix/array.
a = np.arange(1, 51).reshape(5, 10)
print("a =>\n",format(a))
print("a.shape:",format(a.shape))

a =>
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
a.shape: (5, 10)


In [3]:
# revel(): 回傳一個陣列，這個陣列是經過扁平化處理的陣列
# revel(): returns an array that is flattened.
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [4]:
# reshape(): 改變陣列的維度
# reshape(): change the shape of array.
print("a.reshape(5, 2, 5)=>\n{0}".format(a.reshape(5, 2, 5)))

print()
# reshape()可以使用-1的選項讓NumPy自動幫你計算維度大小
# -1 is a option of reshape, that can automatically calcuate the other dimensions.
print("a.reshape(5, 2, -1)=>\n{0}".format(a.reshape(5, 2, -1)))

a.reshape(5, 2, 5)=>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]

a.reshape(5, 2, -1)=>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]


In [5]:
# T: 將陣列或矩陣轉置
# T: Transpose an array or matrix.
b = np.arange(1, 7).reshape(2, 3)
print("b =>\n{0}".format(b))

print()
print("轉置矩陣b(Transpose b.)\n=>\n{0}".format(b.T))

b =>
[[1 2 3]
 [4 5 6]]

轉置矩陣b(Transpose b.)
=>
[[1 4]
 [2 5]
 [3 6]]


In [11]:
##Stacking together different arrays
# 將不同的矩陣堆疊在一起
a = np.arange(1,11).reshape(2,5)
print("a=>\n{0}".format(a))

print()
# Stacking 2 arrays along a horizontal axis.
# 將2個陣列沿著水平軸堆疊起來
print("np.vstack((a,a))=>\n{0}".format(np.vstack((a,a))))

print()
# Stacking 2 arrays along a vertical axis.
# 將2個陣列沿著垂直軸堆疊起來
print("np.hstack((a,a))=>\n{0}".format(np.hstack((a,a))))

a=>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

np.vstack((a,a))=>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]

np.hstack((a,a))=>
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


In [12]:
##Splitting one array into several smaller ones
a = np.round(np.random.random([2,6])*10, 0)
print("a=>\n{0}".format(a))

print()
# hsplit(array, N): 沿著水平軸切成三個矩陣
# hsplit(array, N): Split an array into N arries/matrices along its horizontal axis.
print("np.hsplit(a, 3)=>\n{0}".format(np.hsplit(a, 3)))

print()
# hsplit(array, ())
print("np.hsplit(a, (2,4))=>\n{0}".format(np.hsplit(a, (2,4))))

a=>
[[9. 1. 9. 1. 1. 7.]
 [8. 7. 8. 8. 5. 0.]]

np.hsplit(a, 3)=>
[array([[9., 1.],
       [8., 7.]]), array([[9., 1.],
       [8., 8.]]), array([[1., 7.],
       [5., 0.]])]

np.hsplit(a, (2,4))=>
[array([[9., 1.],
       [8., 7.]]), array([[9., 1.],
       [8., 8.]]), array([[1., 7.],
       [5., 0.]])]
