In [3]:
import numpy as np

In [23]:
##Indexing with Arrays of Indices
a = np.arange(10)**2
print('a=>{0}'.format(a))

print()
i = np.array([1, 3, 5, 7, 9])
print('i=> {0}'.format(i))
print('a[i]=> {1}'.format(i, a[i]))

print()
j = np.array( [[3, 4], [5, 6]] )
print('j=>\n{0}'.format(j))
# Changes shape of a as j, and gets values.
# 把a的形狀改成像j的形狀, 而且取得相對應index的值.
print('a[j]=>\n{0}'.format(a[j]))

a=>[ 0  1  4  9 16 25 36 49 64 81]

i=> [1 3 5 7 9]
a[i]=> [ 1  9 25 49 81]

j=>
[[3 4]
 [5 6]]
a[j]=>
[[ 9 16]
 [25 36]]


In [27]:
x = np.array([[1, 2, 3], [6, 5, 5], [7, 8, 9]])
print(x)
print(x.argmax(axis=0))
print(x.argmax(axis=1))

[[1 2 3]
 [6 5 5]
 [7 8 9]]
[2 2 2]
[2 0 2]
