In [2]:
# This practice is designed for "Basic Operations".
import numpy as np

In [28]:
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
c = a - b
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("c=>{0}".format(c))

# d is squared of b.
d = b**2
print("d=>{0}".format(d))

# 將陣列元素值小於等於0的元素值，取代成1
print("value <= 0 in d:{0}".format(d<=0))
d[d<=0] = 1
print("d=>{0}".format(d))

e = a / d
print("e=>{0}".format(e))

a=>[6 7 8 9]
b=>[0 1 2 3]
c=>[6 6 6 6]
d=>[0 1 4 9]
value <= 0 in d:[ True False False False]
d=>[1 1 4 9]
e=>[6. 7. 2. 1.]


In [32]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A elementwise product B=>\n{0}".format(A*B))

print("A matrix product B =>\n{0}".format(A.dot(B)))

AxB=>
[[ 5 12]
 [21 32]]
A matrix product B =>
[[19 22]
 [43 50]]


In [36]:
## Operations: += *=
a = np.ones((2, 3), dtype=int)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
b += a
# float64 = float64 + int64
print("b=>\n{0}".format(b))

# int64 = int64 + float64
a += b
print("a=>\n{0}".format(a))

a=>
[[5 5 5]
 [5 5 5]]
b=>
[[5.79559739 5.77685238 5.87082873]
 [5.76368142 5.66284714 5.52416567]]


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [42]:
## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("sum=>{0}\nmax=>{1}\nmin=>{2}\nmean=>{3}".format(a.sum(), a.max(), a.min(), a.mean()))

sum=>5.122067675994709
max=>0.9491228462202894
min=>0.1088830369032614
mean=>0.5691186306660787


In [50]:
b = np.arange(12).reshape(2, 6)
print("b=>\n{0}".format(b))

# sum of each column
print("b.sum(axis=0)=>{0}".format(b.sum(axis=0)))

# sum of each row
print("b.sum(axis=0)=>{0}".format(b.sum(axis=1)))

revenu = np.round(np.random.random((1,12)) * 100, 0)
print("revenu=>\n{0}".format(revenu))
print("Cumulative Sum of revenu=>\n{0}".format(revenu.cumsum()))

b=>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
b.sum(axis=0)=>[ 6  8 10 12 14 16]
b.sum(axis=0)=>[15 51]
revenu=>
[[17. 94. 35. 72. 72. 34. 49. 25. 12. 94.  2. 55.]]
Cumulative Sum of revenu=>
[ 17. 111. 146. 218. 290. 324. 373. 398. 410. 504. 506. 561.]
