In [2]:
import numpy as np
import time as t

# Save variables using Numpy
- We will introduce the savez() and savez_compressed() of Numpy to save the variables in python.

## numpy.savez("file name", var1=var1, var2=var2, ...)
- Save several variables in a **uncompressed** .npz file.
- Variables' name:
    - You can assign a new variable name for the variable you attempt to save. Of course, you can use the original variable's name as well.
    - numpy.savez("file name", New name = The variable you want to save)

In [6]:
arr1 = np.arange(1, 101).reshape(10, 10)
arr2 = np.arange(1, 10001).reshape(100, 100)
arr3 = np.arange(1, 1000001).reshape(1000, 1000)

start_time = t.time()
np.savez('example_savez.npz', my_arr1=arr1, my_arr2=arr2, my_arr3=arr3)
end_time = t.time()
print('Time cost: {0} sec.'.format(end_time - start_time))

Time cost: 0.07606315612792969 sec.


## numpy.savez_compressed("file name", var1=var1, var2=var2, ...)
- Save sereral variables in a **compressed** .npz file.

In [8]:
arr4 = np.arange(1, 101).reshape(10, 10)
arr5 = np.arange(1, 10001).reshape(100, 100)
arr6 = np.arange(1, 1000001).reshape(1000, 1000)

start_time = t.time()
np.savez_compressed('example_savez_compressed.npz', my_arr4=arr4, my_arr5=arr5, my_arr6=arr6)
end_time = t.time()
print('Time cost: {0} sec.'.format(end_time - start_time))

Time cost: 0.62156081199646 sec.


## numpy.load("file name")
- Load **.npz** file to your program.

In [9]:
npz_file = np.load('example_savez_compressed.npz')
new_arr4, new_arr5 = npz_file['my_arr4'], npz_file['my_arr5']

print('Shape of new_arr4: {0}'.format(new_arr4.shape))
print(new_arr4)
print('Shape of new_arr5: {0}'.format(new_arr5.shape))


Shape of new_arr4: (10, 10)
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Shape of new_arr5: (100, 100)
