In [1]:
## This lesson is designed for "Printing Arrays"
import numpy as np

In [2]:
# 1-D
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
# 2-D
b = np.arange(12).reshape(2, 6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [26]:
# 3-D
c = np.arange(24).reshape(2,4,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [53]:
# 當要列印的陣列太大時，NumPy會自動以...代替一部分的內容，以減少篇幅！
np.set_printoptions(threshold=1000)
print("NumPy set_printoptions(threshold=default(1000))\n", np.arange(1100))

print()
# 但是可以透過全域設定set_printoptions設定threshold一個門檻值，低於或等於門檻值的陣列就會全部列印出來，相反地高於門檻值得陣列就會減少列印篇幅喔。
# threshold預設值是:1000
# ref: https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html
np.set_printoptions(threshold=200)
print("NumPy set_printoptions(threshold=200)\n", np.arange(50))

NumPy set_printoptions(threshold=default(1000))
 [   0    1    2 ... 1097 1098 1099]

NumPy set_printoptions(threshold=200)
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]
