In [2]:
# This practice is designed for "Basic Operations".
import numpy as np

In [3]:
print('維度相同的矩陣相加、減:')
# 維度相同的矩陣相加、減
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
c = a - b
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("c=>{0}".format(c))


print('\n同加、同減一個數值:')
# 同加、同減一個數值
a += 5
print("a=>{0}".format(a))
b -= 5
print("b=>{0}".format(b))


print('\n次方：')
# d是b的2次方
# d is squared of b.
d = b**2
print("d=>{0}".format(d))

維度相同的矩陣相加、減:
a=>[6 7 8 9]
b=>[0 1 2 3]
c=>[6 6 6 6]

同加、同減一個數值:
a=>[11 12 13 14]
b=>[-5 -4 -3 -2]

次方：
d=>[25 16  9  4]


In [4]:
a = np.arange(5)
b = np.arange(10, 5, -1)
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("\n同除:")
# c等於a同除以2
c = a / 2
print("c=>{0}".format(c))

print("\n同乘:")
# d等於b同乘以2
d = b * 2
print("d=>{0}".format(b))

a=>[0 1 2 3 4]
b=>[10  9  8  7  6]

同除:
c=>[0.  0.5 1.  1.5 2. ]

同乘:
d=>[10  9  8  7  6]


In [6]:
# 矩陣相乘
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A, B相乘(矩陣乘法) =>\n{0}".format(A.dot(B)))
print()
print("A, B相對應位置相乘=>\n{0}".format(A*B))

A, B相乘(矩陣乘法) =>
[[19 22]
 [43 50]]

A, B相對應位置相乘=>
[[ 5 12]
 [21 32]]


In [11]:
# 印出陣列中小於等於0的元素
e = np.array([5, -1, 3, 9, 0])
print("陣列e裡面哪幾個位置的元素值小於等於零?:{0}".format(e<=0))

# 把小於等於0的元素取代成1
e[e<=0] = 1
print("把小於等於0的元素取代成1=>{0}".format(e))

陣列e裡面哪幾個位置的元素值小於等於零?:[False  True False False  True]
把小於等於0的元素取代成1=>[5 1 3 9 1]


In [17]:
## Operations: += *=
a = np.ones((2, 3), dtype=np.float)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
b += a

print("b=>\n{0}".format(b))


a += b
print("a=>\n{0}".format(a))

a=>
[[5. 5. 5.]
 [5. 5. 5.]]
b=>
[[5.54183799 5.417976   5.8559411 ]
 [5.92448501 5.28735178 5.73039198]]
a=>
[[10.54183799 10.417976   10.8559411 ]
 [10.92448501 10.28735178 10.73039198]]


In [18]:
## Operations: += *=
a = np.ones((2, 3), dtype=np.int)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
b += a
# float64 = float64 + int64
print("b=>\n{0}".format(b))

# int64 = int64 + float64
a += b
print("a=>\n{0}".format(a))

a=>
[[5 5 5]
 [5 5 5]]
b=>
[[5.38047447 5.23668611 5.9057241 ]
 [5.62997161 5.45062956 5.12463863]]


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [6]:
## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("sum=>{0}\nmax=>{1}\nmin=>{2}\nmean=>{3}".format(a.sum(), a.max(), a.min(), a.mean()))

sum=>4.749391952733504
max=>0.9580529936101387
min=>0.13855036514445263
mean=>0.5277102169703893


In [19]:
b = np.arange(12).reshape(2, 6)
print("b=>\n{0}".format(b))

print()
# 加總每一欄(column)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=0)))

print()
# 加總每一列(row)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=1)))

print()
revenu = np.round(np.random.random((1,12)) * 100, 0)
print("revenu=>\n{0}".format(revenu))

print()
# 累計加總(每一項數值等於自己加上前一項)
print("Cumulative Sum of revenu=>\n{0}".format(revenu.cumsum()))

b=>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

b.sum(axis=0)=>[ 6  8 10 12 14 16]

b.sum(axis=0)=>[15 51]

revenu=>
[[57. 53. 51. 42. 52. 61. 61. 30. 30. 14. 93. 62.]]

Cumulative Sum of revenu=>
[ 57. 110. 161. 203. 255. 316. 377. 407. 437. 451. 544. 606.]
